version: "3.9"
services:
 # ollama:
  #  image: ollama/ollama
   # container_name: ollama
    #ports:
     # - "11434:11434"
   # volumes:
    #  - ollama_data:/root/.ollama

  pipeline:
    build: .
    container_name: pipeline-api
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_BASE_URL=http://172.17.0.1:11434
      - GDRIVE_CREDENTIALS_PATH=/app/credentials.json
      - GDRIVE_FOLDER_ID=${GDRIVE_FOLDER_ID}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
    volumes:
      - ./credentials.json:/app/credentials.json:ro
      - ./token.json:/app/token.json
    #depends_on:
     # - ollama
    extra_hosts:
      - "host-gateway:host-gateway"
volumes:
  ollama_data:
